services:
  - type: web
    name: your-backend-service
    env: python
    buildCommand: |
      python -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn ecomm_backend.wsgi:application