# Generated by Django 5.0.6 on 2024-06-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SPORTS', 'Sports'), ('FOODS', 'Foods'), ('ACCESSORIES', 'Accessories'), ('CLOTHING', 'Clothing')], default='SPORTS', max_length=20),
        ),
    ]
